// Generated by Finicky Kickstart 
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Safari",      
  handlers: [
    {
      match: /^https?:\/\/meet\.jsteuernagel\.de\/.*$/,
      browser: "Google Chrome"
    },
    {
      match: /^https?:\/\/dhow\-stuttgart\.zoom\.us\/.*$/,
      browser: "Google Chrome"
    }
  ]
}
