#! /bin/sh

type=$1
device=$2
status=$3
#laptop=LVDS1
any_monitor=HDMI-1
any_monitor2=VGA-1
home_monitor=HDMI-3

echo "$type"
echo "$device"
echo "$status"

case "$type,$device,$status" in
  keyboard,*,connected)
    setxkbmap -layout de
    ;;
  display,"$home_monitor",connected)
    TMP=$(echo -e "True\nFalse" | dmenu -p "Switch outputs?")
    if [ "$TMP" = "True" ]; then
      autorandr -l docked --force
      nmcli r wifi off
      killall xautolock
      feh --randomize --bg-scale /home/jonatan/Pictures/Wallpapers
      pactl set-card-profile 0 output:hdmi-stereo-extra2
    fi
	;;
  display,"$home_monitor",disconnected)
    autorandr -l mobile --force
    nmcli r wifi on
    xautolock -time 15 -locker lock &
    feh --randomize --bg-scale /home/jonatan/Pictures/Wallpapers
    pactl set-card-profile 0 output:analog-stereo+input:analog-stereo
    ;;
  display,"$any_monitor",connected)
    autorandr horizontal
    feh --randomize --bg-scale /home/jonatan/Pictures/Wallpapers
    ;;
  display,"$any_monitor",disconnected)
    autorandr -l mobile --force
    feh --randomize --bg-scale /home/jonatan/Pictures/Wallpapers
    ;;
  display,"$any_monitor2",connected)
    autorandr horizontal
    feh --randomize --bg-scale /home/jonatan/Pictures/Wallpapers
    ;;
  display,"$any_monitor2",disconnected)
    autorandr -l mobile --force
    feh --randomize --bg-scale /home/jonatan/Pictures/Wallpapers
    ;;
esac
